// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: games.sql

package db

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const countGames = `-- name: CountGames :one
SELECT count(*) FROM games
WHERE (name ILIKE '%' || $1 || '%' OR $1 IS NULL)
`

func (q *Queries) CountGames(ctx context.Context, searchQuery *string) (int64, error) {
	row := q.db.QueryRow(ctx, countGames, searchQuery)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const createGame = `-- name: CreateGame :one
INSERT INTO games (name, organizer, starts_at, ends_at, avatar_url, site_url, ctftime_url,
    finalized, finalized_at, registration_opens_at, registration_closes_at,
    scoreboard_opens_at, scoreboard_closes_at, vpn_url, vpn_config_url,
    access_instructions, access_secret)
VALUES ($1, $2, $3, $4, $5, $6, $7, $8, $9, $10, $11, $12, $13, $14, $15, $16, $17)
RETURNING id, name, organizer, starts_at, ends_at, created_at, updated_at, avatar_url, site_url, ctftime_url, finalized, finalized_at, registration_opens_at, registration_closes_at, scoreboard_opens_at, scoreboard_closes_at, vpn_url, vpn_config_url, access_instructions, access_secret
`

type CreateGameParams struct {
	Name                 *string            `json:"name"`
	Organizer            *string            `json:"organizer"`
	StartsAt             pgtype.Timestamptz `json:"starts_at"`
	EndsAt               pgtype.Timestamptz `json:"ends_at"`
	AvatarUrl            *string            `json:"avatar_url"`
	SiteUrl              *string            `json:"site_url"`
	CtftimeUrl           *string            `json:"ctftime_url"`
	Finalized            bool               `json:"finalized"`
	FinalizedAt          pgtype.Timestamptz `json:"finalized_at"`
	RegistrationOpensAt  pgtype.Timestamptz `json:"registration_opens_at"`
	RegistrationClosesAt pgtype.Timestamptz `json:"registration_closes_at"`
	ScoreboardOpensAt    pgtype.Timestamptz `json:"scoreboard_opens_at"`
	ScoreboardClosesAt   pgtype.Timestamptz `json:"scoreboard_closes_at"`
	VpnUrl               *string            `json:"vpn_url"`
	VpnConfigUrl         *string            `json:"vpn_config_url"`
	AccessInstructions   *string            `json:"access_instructions"`
	AccessSecret         *string            `json:"access_secret"`
}

func (q *Queries) CreateGame(ctx context.Context, arg CreateGameParams) (Game, error) {
	row := q.db.QueryRow(ctx, createGame,
		arg.Name,
		arg.Organizer,
		arg.StartsAt,
		arg.EndsAt,
		arg.AvatarUrl,
		arg.SiteUrl,
		arg.CtftimeUrl,
		arg.Finalized,
		arg.FinalizedAt,
		arg.RegistrationOpensAt,
		arg.RegistrationClosesAt,
		arg.ScoreboardOpensAt,
		arg.ScoreboardClosesAt,
		arg.VpnUrl,
		arg.VpnConfigUrl,
		arg.AccessInstructions,
		arg.AccessSecret,
	)
	var i Game
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Organizer,
		&i.StartsAt,
		&i.EndsAt,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.AvatarUrl,
		&i.SiteUrl,
		&i.CtftimeUrl,
		&i.Finalized,
		&i.FinalizedAt,
		&i.RegistrationOpensAt,
		&i.RegistrationClosesAt,
		&i.ScoreboardOpensAt,
		&i.ScoreboardClosesAt,
		&i.VpnUrl,
		&i.VpnConfigUrl,
		&i.AccessInstructions,
		&i.AccessSecret,
	)
	return i, err
}

const deleteGame = `-- name: DeleteGame :exec
DELETE FROM games WHERE id = $1
`

func (q *Queries) DeleteGame(ctx context.Context, id int64) error {
	_, err := q.db.Exec(ctx, deleteGame, id)
	return err
}

const getGameByID = `-- name: GetGameByID :one
SELECT id, name, organizer, starts_at, ends_at, created_at, updated_at, avatar_url, site_url, ctftime_url, finalized, finalized_at, registration_opens_at, registration_closes_at, scoreboard_opens_at, scoreboard_closes_at, vpn_url, vpn_config_url, access_instructions, access_secret FROM games WHERE id = $1
`

func (q *Queries) GetGameByID(ctx context.Context, id int64) (Game, error) {
	row := q.db.QueryRow(ctx, getGameByID, id)
	var i Game
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Organizer,
		&i.StartsAt,
		&i.EndsAt,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.AvatarUrl,
		&i.SiteUrl,
		&i.CtftimeUrl,
		&i.Finalized,
		&i.FinalizedAt,
		&i.RegistrationOpensAt,
		&i.RegistrationClosesAt,
		&i.ScoreboardOpensAt,
		&i.ScoreboardClosesAt,
		&i.VpnUrl,
		&i.VpnConfigUrl,
		&i.AccessInstructions,
		&i.AccessSecret,
	)
	return i, err
}

const listGames = `-- name: ListGames :many
SELECT id, name, organizer, starts_at, ends_at, created_at, updated_at, avatar_url, site_url, ctftime_url, finalized, finalized_at, registration_opens_at, registration_closes_at, scoreboard_opens_at, scoreboard_closes_at, vpn_url, vpn_config_url, access_instructions, access_secret FROM games
WHERE (name ILIKE '%' || $3 || '%' OR $3 IS NULL)
ORDER BY starts_at DESC NULLS LAST, created_at DESC, id DESC
LIMIT $1 OFFSET $2
`

type ListGamesParams struct {
	Limit       int32   `json:"limit"`
	Offset      int32   `json:"offset"`
	SearchQuery *string `json:"search_query"`
}

func (q *Queries) ListGames(ctx context.Context, arg ListGamesParams) ([]Game, error) {
	rows, err := q.db.Query(ctx, listGames, arg.Limit, arg.Offset, arg.SearchQuery)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Game
	for rows.Next() {
		var i Game
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.Organizer,
			&i.StartsAt,
			&i.EndsAt,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.AvatarUrl,
			&i.SiteUrl,
			&i.CtftimeUrl,
			&i.Finalized,
			&i.FinalizedAt,
			&i.RegistrationOpensAt,
			&i.RegistrationClosesAt,
			&i.ScoreboardOpensAt,
			&i.ScoreboardClosesAt,
			&i.VpnUrl,
			&i.VpnConfigUrl,
			&i.AccessInstructions,
			&i.AccessSecret,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const setFinalized = `-- name: SetFinalized :one
UPDATE games SET finalized = $2, finalized_at = $3, updated_at = now()
WHERE id = $1
RETURNING id, name, organizer, starts_at, ends_at, created_at, updated_at, avatar_url, site_url, ctftime_url, finalized, finalized_at, registration_opens_at, registration_closes_at, scoreboard_opens_at, scoreboard_closes_at, vpn_url, vpn_config_url, access_instructions, access_secret
`

type SetFinalizedParams struct {
	ID          int64              `json:"id"`
	Finalized   bool               `json:"finalized"`
	FinalizedAt pgtype.Timestamptz `json:"finalized_at"`
}

func (q *Queries) SetFinalized(ctx context.Context, arg SetFinalizedParams) (Game, error) {
	row := q.db.QueryRow(ctx, setFinalized, arg.ID, arg.Finalized, arg.FinalizedAt)
	var i Game
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Organizer,
		&i.StartsAt,
		&i.EndsAt,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.AvatarUrl,
		&i.SiteUrl,
		&i.CtftimeUrl,
		&i.Finalized,
		&i.FinalizedAt,
		&i.RegistrationOpensAt,
		&i.RegistrationClosesAt,
		&i.ScoreboardOpensAt,
		&i.ScoreboardClosesAt,
		&i.VpnUrl,
		&i.VpnConfigUrl,
		&i.AccessInstructions,
		&i.AccessSecret,
	)
	return i, err
}

const updateGame = `-- name: UpdateGame :one
UPDATE games SET
    name = COALESCE($2, name),
    organizer = COALESCE($3, organizer),
    starts_at = COALESCE($4, starts_at),
    ends_at = COALESCE($5, ends_at),
    avatar_url = COALESCE($6, avatar_url),
    site_url = COALESCE($7, site_url),
    ctftime_url = COALESCE($8, ctftime_url),
    registration_opens_at = COALESCE($9, registration_opens_at),
    registration_closes_at = COALESCE($10, registration_closes_at),
    scoreboard_opens_at = COALESCE($11, scoreboard_opens_at),
    scoreboard_closes_at = COALESCE($12, scoreboard_closes_at),
    vpn_url = COALESCE($13, vpn_url),
    vpn_config_url = COALESCE($14, vpn_config_url),
    access_instructions = COALESCE($15, access_instructions),
    access_secret = COALESCE($16, access_secret),
    updated_at = now()
WHERE id = $1
RETURNING id, name, organizer, starts_at, ends_at, created_at, updated_at, avatar_url, site_url, ctftime_url, finalized, finalized_at, registration_opens_at, registration_closes_at, scoreboard_opens_at, scoreboard_closes_at, vpn_url, vpn_config_url, access_instructions, access_secret
`

type UpdateGameParams struct {
	ID                   int64              `json:"id"`
	Name                 *string            `json:"name"`
	Organizer            *string            `json:"organizer"`
	StartsAt             pgtype.Timestamptz `json:"starts_at"`
	EndsAt               pgtype.Timestamptz `json:"ends_at"`
	AvatarUrl            *string            `json:"avatar_url"`
	SiteUrl              *string            `json:"site_url"`
	CtftimeUrl           *string            `json:"ctftime_url"`
	RegistrationOpensAt  pgtype.Timestamptz `json:"registration_opens_at"`
	RegistrationClosesAt pgtype.Timestamptz `json:"registration_closes_at"`
	ScoreboardOpensAt    pgtype.Timestamptz `json:"scoreboard_opens_at"`
	ScoreboardClosesAt   pgtype.Timestamptz `json:"scoreboard_closes_at"`
	VpnUrl               *string            `json:"vpn_url"`
	VpnConfigUrl         *string            `json:"vpn_config_url"`
	AccessInstructions   *string            `json:"access_instructions"`
	AccessSecret         *string            `json:"access_secret"`
}

func (q *Queries) UpdateGame(ctx context.Context, arg UpdateGameParams) (Game, error) {
	row := q.db.QueryRow(ctx, updateGame,
		arg.ID,
		arg.Name,
		arg.Organizer,
		arg.StartsAt,
		arg.EndsAt,
		arg.AvatarUrl,
		arg.SiteUrl,
		arg.CtftimeUrl,
		arg.RegistrationOpensAt,
		arg.RegistrationClosesAt,
		arg.ScoreboardOpensAt,
		arg.ScoreboardClosesAt,
		arg.VpnUrl,
		arg.VpnConfigUrl,
		arg.AccessInstructions,
		arg.AccessSecret,
	)
	var i Game
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Organizer,
		&i.StartsAt,
		&i.EndsAt,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.AvatarUrl,
		&i.SiteUrl,
		&i.CtftimeUrl,
		&i.Finalized,
		&i.FinalizedAt,
		&i.RegistrationOpensAt,
		&i.RegistrationClosesAt,
		&i.ScoreboardOpensAt,
		&i.ScoreboardClosesAt,
		&i.VpnUrl,
		&i.VpnConfigUrl,
		&i.AccessInstructions,
		&i.AccessSecret,
	)
	return i, err
}
