// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: game_teams.sql

package db

import (
	"context"
	"encoding/json"
)

const createGameTeam = `-- name: CreateGameTeam :one
INSERT INTO game_teams (game_id, team_id, ip_address, ctf01d_id, ctf01d_overrides, team_type, "order")
VALUES ($1, $2, $3, $4, $5, $6, $7)
RETURNING id, game_id, team_id, ip_address, ctf01d_id, ctf01d_overrides, team_type, "order", created_at, updated_at
`

type CreateGameTeamParams struct {
	GameID          int64           `json:"game_id"`
	TeamID          int64           `json:"team_id"`
	IpAddress       *string         `json:"ip_address"`
	Ctf01dID        *string         `json:"ctf01d_id"`
	Ctf01dOverrides json.RawMessage `json:"ctf01d_overrides"`
	TeamType        *string         `json:"team_type"`
	Order           int32           `json:"order"`
}

func (q *Queries) CreateGameTeam(ctx context.Context, arg CreateGameTeamParams) (GameTeam, error) {
	row := q.db.QueryRow(ctx, createGameTeam,
		arg.GameID,
		arg.TeamID,
		arg.IpAddress,
		arg.Ctf01dID,
		arg.Ctf01dOverrides,
		arg.TeamType,
		arg.Order,
	)
	var i GameTeam
	err := row.Scan(
		&i.ID,
		&i.GameID,
		&i.TeamID,
		&i.IpAddress,
		&i.Ctf01dID,
		&i.Ctf01dOverrides,
		&i.TeamType,
		&i.Order,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const deleteGameTeam = `-- name: DeleteGameTeam :exec
DELETE FROM game_teams WHERE id = $1
`

func (q *Queries) DeleteGameTeam(ctx context.Context, id int64) error {
	_, err := q.db.Exec(ctx, deleteGameTeam, id)
	return err
}

const getGameTeamByID = `-- name: GetGameTeamByID :one
SELECT id, game_id, team_id, ip_address, ctf01d_id, ctf01d_overrides, team_type, "order", created_at, updated_at FROM game_teams WHERE id = $1
`

func (q *Queries) GetGameTeamByID(ctx context.Context, id int64) (GameTeam, error) {
	row := q.db.QueryRow(ctx, getGameTeamByID, id)
	var i GameTeam
	err := row.Scan(
		&i.ID,
		&i.GameID,
		&i.TeamID,
		&i.IpAddress,
		&i.Ctf01dID,
		&i.Ctf01dOverrides,
		&i.TeamType,
		&i.Order,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const isUserApprovedInGameTeams = `-- name: IsUserApprovedInGameTeams :one
SELECT EXISTS(
  SELECT 1 FROM game_teams gt
  JOIN team_memberships tm ON tm.team_id = gt.team_id AND tm.user_id = $2 AND tm.status = 'approved'
  WHERE gt.game_id = $1
)
`

type IsUserApprovedInGameTeamsParams struct {
	GameID int64 `json:"game_id"`
	UserID int64 `json:"user_id"`
}

func (q *Queries) IsUserApprovedInGameTeams(ctx context.Context, arg IsUserApprovedInGameTeamsParams) (bool, error) {
	row := q.db.QueryRow(ctx, isUserApprovedInGameTeams, arg.GameID, arg.UserID)
	var exists bool
	err := row.Scan(&exists)
	return exists, err
}

const listGameTeamsByGame = `-- name: ListGameTeamsByGame :many
SELECT id, game_id, team_id, ip_address, ctf01d_id, ctf01d_overrides, team_type, "order", created_at, updated_at FROM game_teams WHERE game_id = $1 ORDER BY "order", id
`

func (q *Queries) ListGameTeamsByGame(ctx context.Context, gameID int64) ([]GameTeam, error) {
	rows, err := q.db.Query(ctx, listGameTeamsByGame, gameID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []GameTeam
	for rows.Next() {
		var i GameTeam
		if err := rows.Scan(
			&i.ID,
			&i.GameID,
			&i.TeamID,
			&i.IpAddress,
			&i.Ctf01dID,
			&i.Ctf01dOverrides,
			&i.TeamType,
			&i.Order,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listGameTeamsByTeam = `-- name: ListGameTeamsByTeam :many
SELECT id, game_id, team_id, ip_address, ctf01d_id, ctf01d_overrides, team_type, "order", created_at, updated_at FROM game_teams WHERE team_id = $1
`

func (q *Queries) ListGameTeamsByTeam(ctx context.Context, teamID int64) ([]GameTeam, error) {
	rows, err := q.db.Query(ctx, listGameTeamsByTeam, teamID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []GameTeam
	for rows.Next() {
		var i GameTeam
		if err := rows.Scan(
			&i.ID,
			&i.GameID,
			&i.TeamID,
			&i.IpAddress,
			&i.Ctf01dID,
			&i.Ctf01dOverrides,
			&i.TeamType,
			&i.Order,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateGameTeam = `-- name: UpdateGameTeam :one
UPDATE game_teams SET
    ip_address = COALESCE($2, ip_address),
    ctf01d_id = COALESCE($3, ctf01d_id),
    ctf01d_overrides = COALESCE($4, ctf01d_overrides),
    team_type = COALESCE($5, team_type),
    "order" = COALESCE($6, "order"),
    updated_at = now()
WHERE id = $1
RETURNING id, game_id, team_id, ip_address, ctf01d_id, ctf01d_overrides, team_type, "order", created_at, updated_at
`

type UpdateGameTeamParams struct {
	ID              int64           `json:"id"`
	IpAddress       *string         `json:"ip_address"`
	Ctf01dID        *string         `json:"ctf01d_id"`
	Ctf01dOverrides json.RawMessage `json:"ctf01d_overrides"`
	TeamType        *string         `json:"team_type"`
	Order           int32           `json:"order"`
}

func (q *Queries) UpdateGameTeam(ctx context.Context, arg UpdateGameTeamParams) (GameTeam, error) {
	row := q.db.QueryRow(ctx, updateGameTeam,
		arg.ID,
		arg.IpAddress,
		arg.Ctf01dID,
		arg.Ctf01dOverrides,
		arg.TeamType,
		arg.Order,
	)
	var i GameTeam
	err := row.Scan(
		&i.ID,
		&i.GameID,
		&i.TeamID,
		&i.IpAddress,
		&i.Ctf01dID,
		&i.Ctf01dOverrides,
		&i.TeamType,
		&i.Order,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const updateGameTeamOrder = `-- name: UpdateGameTeamOrder :exec
UPDATE game_teams SET "order" = $2, updated_at = now()
WHERE id = $1
`

type UpdateGameTeamOrderParams struct {
	ID    int64 `json:"id"`
	Order int32 `json:"order"`
}

func (q *Queries) UpdateGameTeamOrder(ctx context.Context, arg UpdateGameTeamOrderParams) error {
	_, err := q.db.Exec(ctx, updateGameTeamOrder, arg.ID, arg.Order)
	return err
}
