// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: services.sql

package db

import (
	"context"
	"encoding/json"

	"github.com/jackc/pgx/v5/pgtype"
)

const countServices = `-- name: CountServices :one
SELECT count(*) FROM services
WHERE ($1::boolean IS NULL OR public = $1)
  AND ($2::text IS NULL OR name ILIKE '%' || $2 || '%')
`

type CountServicesParams struct {
	Column1 bool   `json:"column_1"`
	Column2 string `json:"column_2"`
}

func (q *Queries) CountServices(ctx context.Context, arg CountServicesParams) (int64, error) {
	row := q.db.QueryRow(ctx, countServices, arg.Column1, arg.Column2)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const createService = `-- name: CreateService :one
INSERT INTO services (name, public_description, private_description, author, copyright,
    avatar_url, public, service_archive_url, checker_archive_url, writeup_url, exploits_url,
    check_status, ctf01d_training)
VALUES ($1, $2, $3, $4, $5, $6, $7, $8, $9, $10, $11, $12, $13)
RETURNING id, name, public_description, private_description, author, copyright, avatar_url, public, created_at, updated_at, service_archive_url, checker_archive_url, writeup_url, exploits_url, check_status, checked_at, service_local_path, service_local_size, service_local_sha256, service_downloaded_at, checker_local_path, checker_local_size, checker_local_sha256, checker_downloaded_at, ctf01d_training
`

type CreateServiceParams struct {
	Name               string          `json:"name"`
	PublicDescription  *string         `json:"public_description"`
	PrivateDescription *string         `json:"private_description"`
	Author             *string         `json:"author"`
	Copyright          *string         `json:"copyright"`
	AvatarUrl          *string         `json:"avatar_url"`
	Public             bool            `json:"public"`
	ServiceArchiveUrl  *string         `json:"service_archive_url"`
	CheckerArchiveUrl  *string         `json:"checker_archive_url"`
	WriteupUrl         *string         `json:"writeup_url"`
	ExploitsUrl        *string         `json:"exploits_url"`
	CheckStatus        string          `json:"check_status"`
	Ctf01dTraining     json.RawMessage `json:"ctf01d_training"`
}

func (q *Queries) CreateService(ctx context.Context, arg CreateServiceParams) (Service, error) {
	row := q.db.QueryRow(ctx, createService,
		arg.Name,
		arg.PublicDescription,
		arg.PrivateDescription,
		arg.Author,
		arg.Copyright,
		arg.AvatarUrl,
		arg.Public,
		arg.ServiceArchiveUrl,
		arg.CheckerArchiveUrl,
		arg.WriteupUrl,
		arg.ExploitsUrl,
		arg.CheckStatus,
		arg.Ctf01dTraining,
	)
	var i Service
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.PublicDescription,
		&i.PrivateDescription,
		&i.Author,
		&i.Copyright,
		&i.AvatarUrl,
		&i.Public,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.ServiceArchiveUrl,
		&i.CheckerArchiveUrl,
		&i.WriteupUrl,
		&i.ExploitsUrl,
		&i.CheckStatus,
		&i.CheckedAt,
		&i.ServiceLocalPath,
		&i.ServiceLocalSize,
		&i.ServiceLocalSha256,
		&i.ServiceDownloadedAt,
		&i.CheckerLocalPath,
		&i.CheckerLocalSize,
		&i.CheckerLocalSha256,
		&i.CheckerDownloadedAt,
		&i.Ctf01dTraining,
	)
	return i, err
}

const deleteService = `-- name: DeleteService :exec
DELETE FROM services WHERE id = $1
`

func (q *Queries) DeleteService(ctx context.Context, id int64) error {
	_, err := q.db.Exec(ctx, deleteService, id)
	return err
}

const getServiceByID = `-- name: GetServiceByID :one
SELECT id, name, public_description, private_description, author, copyright, avatar_url, public, created_at, updated_at, service_archive_url, checker_archive_url, writeup_url, exploits_url, check_status, checked_at, service_local_path, service_local_size, service_local_sha256, service_downloaded_at, checker_local_path, checker_local_size, checker_local_sha256, checker_downloaded_at, ctf01d_training FROM services WHERE id = $1
`

func (q *Queries) GetServiceByID(ctx context.Context, id int64) (Service, error) {
	row := q.db.QueryRow(ctx, getServiceByID, id)
	var i Service
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.PublicDescription,
		&i.PrivateDescription,
		&i.Author,
		&i.Copyright,
		&i.AvatarUrl,
		&i.Public,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.ServiceArchiveUrl,
		&i.CheckerArchiveUrl,
		&i.WriteupUrl,
		&i.ExploitsUrl,
		&i.CheckStatus,
		&i.CheckedAt,
		&i.ServiceLocalPath,
		&i.ServiceLocalSize,
		&i.ServiceLocalSha256,
		&i.ServiceDownloadedAt,
		&i.CheckerLocalPath,
		&i.CheckerLocalSize,
		&i.CheckerLocalSha256,
		&i.CheckerDownloadedAt,
		&i.Ctf01dTraining,
	)
	return i, err
}

const getServiceByName = `-- name: GetServiceByName :one
SELECT id, name, public_description, private_description, author, copyright, avatar_url, public, created_at, updated_at, service_archive_url, checker_archive_url, writeup_url, exploits_url, check_status, checked_at, service_local_path, service_local_size, service_local_sha256, service_downloaded_at, checker_local_path, checker_local_size, checker_local_sha256, checker_downloaded_at, ctf01d_training FROM services WHERE name = $1
`

func (q *Queries) GetServiceByName(ctx context.Context, name string) (Service, error) {
	row := q.db.QueryRow(ctx, getServiceByName, name)
	var i Service
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.PublicDescription,
		&i.PrivateDescription,
		&i.Author,
		&i.Copyright,
		&i.AvatarUrl,
		&i.Public,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.ServiceArchiveUrl,
		&i.CheckerArchiveUrl,
		&i.WriteupUrl,
		&i.ExploitsUrl,
		&i.CheckStatus,
		&i.CheckedAt,
		&i.ServiceLocalPath,
		&i.ServiceLocalSize,
		&i.ServiceLocalSha256,
		&i.ServiceDownloadedAt,
		&i.CheckerLocalPath,
		&i.CheckerLocalSize,
		&i.CheckerLocalSha256,
		&i.CheckerDownloadedAt,
		&i.Ctf01dTraining,
	)
	return i, err
}

const listServices = `-- name: ListServices :many
SELECT id, name, public_description, private_description, author, copyright, avatar_url, public, created_at, updated_at, service_archive_url, checker_archive_url, writeup_url, exploits_url, check_status, checked_at, service_local_path, service_local_size, service_local_sha256, service_downloaded_at, checker_local_path, checker_local_size, checker_local_sha256, checker_downloaded_at, ctf01d_training FROM services
WHERE ($1::boolean IS NULL OR public = $1)
  AND ($2::text IS NULL OR name ILIKE '%' || $2 || '%')
ORDER BY id
LIMIT $3 OFFSET $4
`

type ListServicesParams struct {
	Column1 bool   `json:"column_1"`
	Column2 string `json:"column_2"`
	Limit   int32  `json:"limit"`
	Offset  int32  `json:"offset"`
}

func (q *Queries) ListServices(ctx context.Context, arg ListServicesParams) ([]Service, error) {
	rows, err := q.db.Query(ctx, listServices,
		arg.Column1,
		arg.Column2,
		arg.Limit,
		arg.Offset,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Service
	for rows.Next() {
		var i Service
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.PublicDescription,
			&i.PrivateDescription,
			&i.Author,
			&i.Copyright,
			&i.AvatarUrl,
			&i.Public,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.ServiceArchiveUrl,
			&i.CheckerArchiveUrl,
			&i.WriteupUrl,
			&i.ExploitsUrl,
			&i.CheckStatus,
			&i.CheckedAt,
			&i.ServiceLocalPath,
			&i.ServiceLocalSize,
			&i.ServiceLocalSha256,
			&i.ServiceDownloadedAt,
			&i.CheckerLocalPath,
			&i.CheckerLocalSize,
			&i.CheckerLocalSha256,
			&i.CheckerDownloadedAt,
			&i.Ctf01dTraining,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const setArchiveURLs = `-- name: SetArchiveURLs :one
UPDATE services SET
    service_archive_url = COALESCE($2, service_archive_url),
    checker_archive_url = COALESCE($3, checker_archive_url),
    updated_at = now()
WHERE id = $1
RETURNING id, name, public_description, private_description, author, copyright, avatar_url, public, created_at, updated_at, service_archive_url, checker_archive_url, writeup_url, exploits_url, check_status, checked_at, service_local_path, service_local_size, service_local_sha256, service_downloaded_at, checker_local_path, checker_local_size, checker_local_sha256, checker_downloaded_at, ctf01d_training
`

type SetArchiveURLsParams struct {
	ID                int64   `json:"id"`
	ServiceArchiveUrl *string `json:"service_archive_url"`
	CheckerArchiveUrl *string `json:"checker_archive_url"`
}

func (q *Queries) SetArchiveURLs(ctx context.Context, arg SetArchiveURLsParams) (Service, error) {
	row := q.db.QueryRow(ctx, setArchiveURLs, arg.ID, arg.ServiceArchiveUrl, arg.CheckerArchiveUrl)
	var i Service
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.PublicDescription,
		&i.PrivateDescription,
		&i.Author,
		&i.Copyright,
		&i.AvatarUrl,
		&i.Public,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.ServiceArchiveUrl,
		&i.CheckerArchiveUrl,
		&i.WriteupUrl,
		&i.ExploitsUrl,
		&i.CheckStatus,
		&i.CheckedAt,
		&i.ServiceLocalPath,
		&i.ServiceLocalSize,
		&i.ServiceLocalSha256,
		&i.ServiceDownloadedAt,
		&i.CheckerLocalPath,
		&i.CheckerLocalSize,
		&i.CheckerLocalSha256,
		&i.CheckerDownloadedAt,
		&i.Ctf01dTraining,
	)
	return i, err
}

const setCheckStatus = `-- name: SetCheckStatus :one
UPDATE services SET check_status = $2, checked_at = $3, updated_at = now()
WHERE id = $1
RETURNING id, name, public_description, private_description, author, copyright, avatar_url, public, created_at, updated_at, service_archive_url, checker_archive_url, writeup_url, exploits_url, check_status, checked_at, service_local_path, service_local_size, service_local_sha256, service_downloaded_at, checker_local_path, checker_local_size, checker_local_sha256, checker_downloaded_at, ctf01d_training
`

type SetCheckStatusParams struct {
	ID          int64              `json:"id"`
	CheckStatus string             `json:"check_status"`
	CheckedAt   pgtype.Timestamptz `json:"checked_at"`
}

func (q *Queries) SetCheckStatus(ctx context.Context, arg SetCheckStatusParams) (Service, error) {
	row := q.db.QueryRow(ctx, setCheckStatus, arg.ID, arg.CheckStatus, arg.CheckedAt)
	var i Service
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.PublicDescription,
		&i.PrivateDescription,
		&i.Author,
		&i.Copyright,
		&i.AvatarUrl,
		&i.Public,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.ServiceArchiveUrl,
		&i.CheckerArchiveUrl,
		&i.WriteupUrl,
		&i.ExploitsUrl,
		&i.CheckStatus,
		&i.CheckedAt,
		&i.ServiceLocalPath,
		&i.ServiceLocalSize,
		&i.ServiceLocalSha256,
		&i.ServiceDownloadedAt,
		&i.CheckerLocalPath,
		&i.CheckerLocalSize,
		&i.CheckerLocalSha256,
		&i.CheckerDownloadedAt,
		&i.Ctf01dTraining,
	)
	return i, err
}

const setCheckerLocal = `-- name: SetCheckerLocal :one
UPDATE services SET
    checker_local_path = $2,
    checker_local_size = $3,
    checker_local_sha256 = $4,
    checker_downloaded_at = $5,
    updated_at = now()
WHERE id = $1
RETURNING id, name, public_description, private_description, author, copyright, avatar_url, public, created_at, updated_at, service_archive_url, checker_archive_url, writeup_url, exploits_url, check_status, checked_at, service_local_path, service_local_size, service_local_sha256, service_downloaded_at, checker_local_path, checker_local_size, checker_local_sha256, checker_downloaded_at, ctf01d_training
`

type SetCheckerLocalParams struct {
	ID                  int64              `json:"id"`
	CheckerLocalPath    *string            `json:"checker_local_path"`
	CheckerLocalSize    *int32             `json:"checker_local_size"`
	CheckerLocalSha256  *string            `json:"checker_local_sha256"`
	CheckerDownloadedAt pgtype.Timestamptz `json:"checker_downloaded_at"`
}

func (q *Queries) SetCheckerLocal(ctx context.Context, arg SetCheckerLocalParams) (Service, error) {
	row := q.db.QueryRow(ctx, setCheckerLocal,
		arg.ID,
		arg.CheckerLocalPath,
		arg.CheckerLocalSize,
		arg.CheckerLocalSha256,
		arg.CheckerDownloadedAt,
	)
	var i Service
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.PublicDescription,
		&i.PrivateDescription,
		&i.Author,
		&i.Copyright,
		&i.AvatarUrl,
		&i.Public,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.ServiceArchiveUrl,
		&i.CheckerArchiveUrl,
		&i.WriteupUrl,
		&i.ExploitsUrl,
		&i.CheckStatus,
		&i.CheckedAt,
		&i.ServiceLocalPath,
		&i.ServiceLocalSize,
		&i.ServiceLocalSha256,
		&i.ServiceDownloadedAt,
		&i.CheckerLocalPath,
		&i.CheckerLocalSize,
		&i.CheckerLocalSha256,
		&i.CheckerDownloadedAt,
		&i.Ctf01dTraining,
	)
	return i, err
}

const setPublic = `-- name: SetPublic :one
UPDATE services SET public = $2, updated_at = now()
WHERE id = $1
RETURNING id, name, public_description, private_description, author, copyright, avatar_url, public, created_at, updated_at, service_archive_url, checker_archive_url, writeup_url, exploits_url, check_status, checked_at, service_local_path, service_local_size, service_local_sha256, service_downloaded_at, checker_local_path, checker_local_size, checker_local_sha256, checker_downloaded_at, ctf01d_training
`

type SetPublicParams struct {
	ID     int64 `json:"id"`
	Public bool  `json:"public"`
}

func (q *Queries) SetPublic(ctx context.Context, arg SetPublicParams) (Service, error) {
	row := q.db.QueryRow(ctx, setPublic, arg.ID, arg.Public)
	var i Service
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.PublicDescription,
		&i.PrivateDescription,
		&i.Author,
		&i.Copyright,
		&i.AvatarUrl,
		&i.Public,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.ServiceArchiveUrl,
		&i.CheckerArchiveUrl,
		&i.WriteupUrl,
		&i.ExploitsUrl,
		&i.CheckStatus,
		&i.CheckedAt,
		&i.ServiceLocalPath,
		&i.ServiceLocalSize,
		&i.ServiceLocalSha256,
		&i.ServiceDownloadedAt,
		&i.CheckerLocalPath,
		&i.CheckerLocalSize,
		&i.CheckerLocalSha256,
		&i.CheckerDownloadedAt,
		&i.Ctf01dTraining,
	)
	return i, err
}

const setServiceLocal = `-- name: SetServiceLocal :one
UPDATE services SET
    service_local_path = $2,
    service_local_size = $3,
    service_local_sha256 = $4,
    service_downloaded_at = $5,
    updated_at = now()
WHERE id = $1
RETURNING id, name, public_description, private_description, author, copyright, avatar_url, public, created_at, updated_at, service_archive_url, checker_archive_url, writeup_url, exploits_url, check_status, checked_at, service_local_path, service_local_size, service_local_sha256, service_downloaded_at, checker_local_path, checker_local_size, checker_local_sha256, checker_downloaded_at, ctf01d_training
`

type SetServiceLocalParams struct {
	ID                  int64              `json:"id"`
	ServiceLocalPath    *string            `json:"service_local_path"`
	ServiceLocalSize    *int32             `json:"service_local_size"`
	ServiceLocalSha256  *string            `json:"service_local_sha256"`
	ServiceDownloadedAt pgtype.Timestamptz `json:"service_downloaded_at"`
}

func (q *Queries) SetServiceLocal(ctx context.Context, arg SetServiceLocalParams) (Service, error) {
	row := q.db.QueryRow(ctx, setServiceLocal,
		arg.ID,
		arg.ServiceLocalPath,
		arg.ServiceLocalSize,
		arg.ServiceLocalSha256,
		arg.ServiceDownloadedAt,
	)
	var i Service
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.PublicDescription,
		&i.PrivateDescription,
		&i.Author,
		&i.Copyright,
		&i.AvatarUrl,
		&i.Public,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.ServiceArchiveUrl,
		&i.CheckerArchiveUrl,
		&i.WriteupUrl,
		&i.ExploitsUrl,
		&i.CheckStatus,
		&i.CheckedAt,
		&i.ServiceLocalPath,
		&i.ServiceLocalSize,
		&i.ServiceLocalSha256,
		&i.ServiceDownloadedAt,
		&i.CheckerLocalPath,
		&i.CheckerLocalSize,
		&i.CheckerLocalSha256,
		&i.CheckerDownloadedAt,
		&i.Ctf01dTraining,
	)
	return i, err
}

const updateService = `-- name: UpdateService :one
UPDATE services SET
    name = COALESCE($2, name),
    public_description = COALESCE($3, public_description),
    private_description = COALESCE($4, private_description),
    author = COALESCE($5, author),
    copyright = COALESCE($6, copyright),
    avatar_url = COALESCE($7, avatar_url),
    public = COALESCE($8, public),
    service_archive_url = COALESCE($9, service_archive_url),
    checker_archive_url = COALESCE($10, checker_archive_url),
    writeup_url = COALESCE($11, writeup_url),
    exploits_url = COALESCE($12, exploits_url),
    ctf01d_training = COALESCE($13, ctf01d_training),
    updated_at = now()
WHERE id = $1
RETURNING id, name, public_description, private_description, author, copyright, avatar_url, public, created_at, updated_at, service_archive_url, checker_archive_url, writeup_url, exploits_url, check_status, checked_at, service_local_path, service_local_size, service_local_sha256, service_downloaded_at, checker_local_path, checker_local_size, checker_local_sha256, checker_downloaded_at, ctf01d_training
`

type UpdateServiceParams struct {
	ID                 int64           `json:"id"`
	Name               string          `json:"name"`
	PublicDescription  *string         `json:"public_description"`
	PrivateDescription *string         `json:"private_description"`
	Author             *string         `json:"author"`
	Copyright          *string         `json:"copyright"`
	AvatarUrl          *string         `json:"avatar_url"`
	Public             bool            `json:"public"`
	ServiceArchiveUrl  *string         `json:"service_archive_url"`
	CheckerArchiveUrl  *string         `json:"checker_archive_url"`
	WriteupUrl         *string         `json:"writeup_url"`
	ExploitsUrl        *string         `json:"exploits_url"`
	Ctf01dTraining     json.RawMessage `json:"ctf01d_training"`
}

func (q *Queries) UpdateService(ctx context.Context, arg UpdateServiceParams) (Service, error) {
	row := q.db.QueryRow(ctx, updateService,
		arg.ID,
		arg.Name,
		arg.PublicDescription,
		arg.PrivateDescription,
		arg.Author,
		arg.Copyright,
		arg.AvatarUrl,
		arg.Public,
		arg.ServiceArchiveUrl,
		arg.CheckerArchiveUrl,
		arg.WriteupUrl,
		arg.ExploitsUrl,
		arg.Ctf01dTraining,
	)
	var i Service
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.PublicDescription,
		&i.PrivateDescription,
		&i.Author,
		&i.Copyright,
		&i.AvatarUrl,
		&i.Public,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.ServiceArchiveUrl,
		&i.CheckerArchiveUrl,
		&i.WriteupUrl,
		&i.ExploitsUrl,
		&i.CheckStatus,
		&i.CheckedAt,
		&i.ServiceLocalPath,
		&i.ServiceLocalSize,
		&i.ServiceLocalSha256,
		&i.ServiceDownloadedAt,
		&i.CheckerLocalPath,
		&i.CheckerLocalSize,
		&i.CheckerLocalSha256,
		&i.CheckerDownloadedAt,
		&i.Ctf01dTraining,
	)
	return i, err
}
