// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: sessions.sql

package db

import (
	"context"
	"time"

	"github.com/jackc/pgx/v5/pgtype"
)

const createSession = `-- name: CreateSession :one
INSERT INTO user_sessions (user_id, jti, ip_address, user_agent, expires_at)
VALUES ($1, $2, $3, $4, $5)
RETURNING id, user_id, jti, ip_address, user_agent, created_at, last_seen_at, expires_at, revoked_at
`

type CreateSessionParams struct {
	UserID    int64     `json:"user_id"`
	Jti       string    `json:"jti"`
	IpAddress *string   `json:"ip_address"`
	UserAgent *string   `json:"user_agent"`
	ExpiresAt time.Time `json:"expires_at"`
}

func (q *Queries) CreateSession(ctx context.Context, arg CreateSessionParams) (UserSession, error) {
	row := q.db.QueryRow(ctx, createSession,
		arg.UserID,
		arg.Jti,
		arg.IpAddress,
		arg.UserAgent,
		arg.ExpiresAt,
	)
	var i UserSession
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.Jti,
		&i.IpAddress,
		&i.UserAgent,
		&i.CreatedAt,
		&i.LastSeenAt,
		&i.ExpiresAt,
		&i.RevokedAt,
	)
	return i, err
}

const deleteExpiredSessions = `-- name: DeleteExpiredSessions :exec
DELETE FROM user_sessions
WHERE expires_at < now()
`

func (q *Queries) DeleteExpiredSessions(ctx context.Context) error {
	_, err := q.db.Exec(ctx, deleteExpiredSessions)
	return err
}

const getSessionByJTI = `-- name: GetSessionByJTI :one
SELECT id, user_id, jti, ip_address, user_agent, created_at, last_seen_at, expires_at, revoked_at FROM user_sessions
WHERE jti = $1
`

func (q *Queries) GetSessionByJTI(ctx context.Context, jti string) (UserSession, error) {
	row := q.db.QueryRow(ctx, getSessionByJTI, jti)
	var i UserSession
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.Jti,
		&i.IpAddress,
		&i.UserAgent,
		&i.CreatedAt,
		&i.LastSeenAt,
		&i.ExpiresAt,
		&i.RevokedAt,
	)
	return i, err
}

const getSessionForAuth = `-- name: GetSessionForAuth :one
SELECT s.revoked_at, s.expires_at, s.last_seen_at, u.is_blocked
FROM user_sessions s
JOIN users u ON u.id = s.user_id
WHERE s.jti = $1
`

type GetSessionForAuthRow struct {
	RevokedAt  pgtype.Timestamptz `json:"revoked_at"`
	ExpiresAt  time.Time          `json:"expires_at"`
	LastSeenAt time.Time          `json:"last_seen_at"`
	IsBlocked  bool               `json:"is_blocked"`
}

// Single read used on every authenticated request: session validity plus the
// owner's blocked flag, avoiding a second query/lookup.
func (q *Queries) GetSessionForAuth(ctx context.Context, jti string) (GetSessionForAuthRow, error) {
	row := q.db.QueryRow(ctx, getSessionForAuth, jti)
	var i GetSessionForAuthRow
	err := row.Scan(
		&i.RevokedAt,
		&i.ExpiresAt,
		&i.LastSeenAt,
		&i.IsBlocked,
	)
	return i, err
}

const listActiveSessionsByUser = `-- name: ListActiveSessionsByUser :many
SELECT id, user_id, jti, ip_address, user_agent, created_at, last_seen_at, expires_at, revoked_at FROM user_sessions
WHERE user_id = $1
  AND revoked_at IS NULL
  AND expires_at > now()
ORDER BY last_seen_at DESC
`

func (q *Queries) ListActiveSessionsByUser(ctx context.Context, userID int64) ([]UserSession, error) {
	rows, err := q.db.Query(ctx, listActiveSessionsByUser, userID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []UserSession
	for rows.Next() {
		var i UserSession
		if err := rows.Scan(
			&i.ID,
			&i.UserID,
			&i.Jti,
			&i.IpAddress,
			&i.UserAgent,
			&i.CreatedAt,
			&i.LastSeenAt,
			&i.ExpiresAt,
			&i.RevokedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const revokeAllUserSessions = `-- name: RevokeAllUserSessions :exec
UPDATE user_sessions
SET revoked_at = now()
WHERE user_id = $1 AND revoked_at IS NULL
`

func (q *Queries) RevokeAllUserSessions(ctx context.Context, userID int64) error {
	_, err := q.db.Exec(ctx, revokeAllUserSessions, userID)
	return err
}

const revokeSession = `-- name: RevokeSession :exec
UPDATE user_sessions
SET revoked_at = now()
WHERE jti = $1 AND revoked_at IS NULL
`

func (q *Queries) RevokeSession(ctx context.Context, jti string) error {
	_, err := q.db.Exec(ctx, revokeSession, jti)
	return err
}

const revokeSessionByID = `-- name: RevokeSessionByID :exec
UPDATE user_sessions
SET revoked_at = now()
WHERE id = $1 AND user_id = $2 AND revoked_at IS NULL
`

type RevokeSessionByIDParams struct {
	ID     int64 `json:"id"`
	UserID int64 `json:"user_id"`
}

func (q *Queries) RevokeSessionByID(ctx context.Context, arg RevokeSessionByIDParams) error {
	_, err := q.db.Exec(ctx, revokeSessionByID, arg.ID, arg.UserID)
	return err
}

const touchSession = `-- name: TouchSession :exec
UPDATE user_sessions
SET last_seen_at = now(),
    ip_address = COALESCE($2, ip_address)
WHERE jti = $1
`

type TouchSessionParams struct {
	Jti       string  `json:"jti"`
	IpAddress *string `json:"ip_address"`
}

func (q *Queries) TouchSession(ctx context.Context, arg TouchSessionParams) error {
	_, err := q.db.Exec(ctx, touchSession, arg.Jti, arg.IpAddress)
	return err
}
