// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: teams.sql

package db

import (
	"context"
)

const clearCaptain = `-- name: ClearCaptain :one
UPDATE teams SET captain_id = NULL, updated_at = now()
WHERE id = $1 RETURNING id, name, description, website, avatar_url, captain_id, created_at, updated_at, university_id
`

func (q *Queries) ClearCaptain(ctx context.Context, id int64) (Team, error) {
	row := q.db.QueryRow(ctx, clearCaptain, id)
	var i Team
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Description,
		&i.Website,
		&i.AvatarUrl,
		&i.CaptainID,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.UniversityID,
	)
	return i, err
}

const countTeams = `-- name: CountTeams :one
SELECT count(*) FROM teams
WHERE (name ILIKE '%' || $1 || '%' OR $1 IS NULL)
`

func (q *Queries) CountTeams(ctx context.Context, searchQuery *string) (int64, error) {
	row := q.db.QueryRow(ctx, countTeams, searchQuery)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const createTeam = `-- name: CreateTeam :one
INSERT INTO teams (name, description, website, avatar_url, university_id)
VALUES ($1, $2, $3, $4, $5)
RETURNING id, name, description, website, avatar_url, captain_id, created_at, updated_at, university_id
`

type CreateTeamParams struct {
	Name         string  `json:"name"`
	Description  *string `json:"description"`
	Website      *string `json:"website"`
	AvatarUrl    *string `json:"avatar_url"`
	UniversityID *int64  `json:"university_id"`
}

func (q *Queries) CreateTeam(ctx context.Context, arg CreateTeamParams) (Team, error) {
	row := q.db.QueryRow(ctx, createTeam,
		arg.Name,
		arg.Description,
		arg.Website,
		arg.AvatarUrl,
		arg.UniversityID,
	)
	var i Team
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Description,
		&i.Website,
		&i.AvatarUrl,
		&i.CaptainID,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.UniversityID,
	)
	return i, err
}

const deleteTeam = `-- name: DeleteTeam :exec
DELETE FROM teams WHERE id = $1
`

func (q *Queries) DeleteTeam(ctx context.Context, id int64) error {
	_, err := q.db.Exec(ctx, deleteTeam, id)
	return err
}

const getTeamByCaptain = `-- name: GetTeamByCaptain :one
SELECT id, name, description, website, avatar_url, captain_id, created_at, updated_at, university_id FROM teams WHERE captain_id = $1
`

func (q *Queries) GetTeamByCaptain(ctx context.Context, captainID *int32) (Team, error) {
	row := q.db.QueryRow(ctx, getTeamByCaptain, captainID)
	var i Team
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Description,
		&i.Website,
		&i.AvatarUrl,
		&i.CaptainID,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.UniversityID,
	)
	return i, err
}

const getTeamByID = `-- name: GetTeamByID :one
SELECT id, name, description, website, avatar_url, captain_id, created_at, updated_at, university_id FROM teams WHERE id = $1
`

func (q *Queries) GetTeamByID(ctx context.Context, id int64) (Team, error) {
	row := q.db.QueryRow(ctx, getTeamByID, id)
	var i Team
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Description,
		&i.Website,
		&i.AvatarUrl,
		&i.CaptainID,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.UniversityID,
	)
	return i, err
}

const listTeams = `-- name: ListTeams :many
SELECT id, name, description, website, avatar_url, captain_id, created_at, updated_at, university_id FROM teams
WHERE (name ILIKE '%' || $3 || '%' OR $3 IS NULL)
ORDER BY id LIMIT $1 OFFSET $2
`

type ListTeamsParams struct {
	Limit       int32   `json:"limit"`
	Offset      int32   `json:"offset"`
	SearchQuery *string `json:"search_query"`
}

func (q *Queries) ListTeams(ctx context.Context, arg ListTeamsParams) ([]Team, error) {
	rows, err := q.db.Query(ctx, listTeams, arg.Limit, arg.Offset, arg.SearchQuery)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Team
	for rows.Next() {
		var i Team
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.Description,
			&i.Website,
			&i.AvatarUrl,
			&i.CaptainID,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.UniversityID,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const setCaptain = `-- name: SetCaptain :one
UPDATE teams SET captain_id = $2, updated_at = now()
WHERE id = $1 RETURNING id, name, description, website, avatar_url, captain_id, created_at, updated_at, university_id
`

type SetCaptainParams struct {
	ID        int64  `json:"id"`
	CaptainID *int32 `json:"captain_id"`
}

func (q *Queries) SetCaptain(ctx context.Context, arg SetCaptainParams) (Team, error) {
	row := q.db.QueryRow(ctx, setCaptain, arg.ID, arg.CaptainID)
	var i Team
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Description,
		&i.Website,
		&i.AvatarUrl,
		&i.CaptainID,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.UniversityID,
	)
	return i, err
}

const updateTeam = `-- name: UpdateTeam :one
UPDATE teams SET name = COALESCE($2, name),
    description = COALESCE($3, description),
    website = COALESCE($4, website),
    avatar_url = COALESCE($5, avatar_url),
    university_id = COALESCE($6, university_id),
    updated_at = now()
WHERE id = $1 RETURNING id, name, description, website, avatar_url, captain_id, created_at, updated_at, university_id
`

type UpdateTeamParams struct {
	ID           int64   `json:"id"`
	Name         string  `json:"name"`
	Description  *string `json:"description"`
	Website      *string `json:"website"`
	AvatarUrl    *string `json:"avatar_url"`
	UniversityID *int64  `json:"university_id"`
}

func (q *Queries) UpdateTeam(ctx context.Context, arg UpdateTeamParams) (Team, error) {
	row := q.db.QueryRow(ctx, updateTeam,
		arg.ID,
		arg.Name,
		arg.Description,
		arg.Website,
		arg.AvatarUrl,
		arg.UniversityID,
	)
	var i Team
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Description,
		&i.Website,
		&i.AvatarUrl,
		&i.CaptainID,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.UniversityID,
	)
	return i, err
}
