// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: team_memberships.sql

package db

import (
	"context"
)

const countApprovedManagers = `-- name: CountApprovedManagers :one
SELECT count(*) FROM team_memberships
WHERE team_id = $1 AND status = 'approved' AND role IN ('owner', 'captain', 'vice_captain')
`

func (q *Queries) CountApprovedManagers(ctx context.Context, teamID int64) (int64, error) {
	row := q.db.QueryRow(ctx, countApprovedManagers, teamID)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const countTeamMemberships = `-- name: CountTeamMemberships :one
SELECT count(*) FROM team_memberships
`

func (q *Queries) CountTeamMemberships(ctx context.Context) (int64, error) {
	row := q.db.QueryRow(ctx, countTeamMemberships)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const createTeamMembership = `-- name: CreateTeamMembership :one
INSERT INTO team_memberships (team_id, user_id, role, status)
VALUES ($1, $2, $3, $4)
RETURNING id, team_id, user_id, role, status, created_at, updated_at
`

type CreateTeamMembershipParams struct {
	TeamID int64   `json:"team_id"`
	UserID int64   `json:"user_id"`
	Role   *string `json:"role"`
	Status *string `json:"status"`
}

func (q *Queries) CreateTeamMembership(ctx context.Context, arg CreateTeamMembershipParams) (TeamMembership, error) {
	row := q.db.QueryRow(ctx, createTeamMembership,
		arg.TeamID,
		arg.UserID,
		arg.Role,
		arg.Status,
	)
	var i TeamMembership
	err := row.Scan(
		&i.ID,
		&i.TeamID,
		&i.UserID,
		&i.Role,
		&i.Status,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const deleteTeamMembership = `-- name: DeleteTeamMembership :exec
DELETE FROM team_memberships WHERE id = $1
`

func (q *Queries) DeleteTeamMembership(ctx context.Context, id int64) error {
	_, err := q.db.Exec(ctx, deleteTeamMembership, id)
	return err
}

const getMembership = `-- name: GetMembership :one
SELECT id, team_id, user_id, role, status, created_at, updated_at FROM team_memberships WHERE team_id = $1 AND user_id = $2
`

type GetMembershipParams struct {
	TeamID int64 `json:"team_id"`
	UserID int64 `json:"user_id"`
}

func (q *Queries) GetMembership(ctx context.Context, arg GetMembershipParams) (TeamMembership, error) {
	row := q.db.QueryRow(ctx, getMembership, arg.TeamID, arg.UserID)
	var i TeamMembership
	err := row.Scan(
		&i.ID,
		&i.TeamID,
		&i.UserID,
		&i.Role,
		&i.Status,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getTeamMembershipByID = `-- name: GetTeamMembershipByID :one
SELECT id, team_id, user_id, role, status, created_at, updated_at FROM team_memberships WHERE id = $1
`

func (q *Queries) GetTeamMembershipByID(ctx context.Context, id int64) (TeamMembership, error) {
	row := q.db.QueryRow(ctx, getTeamMembershipByID, id)
	var i TeamMembership
	err := row.Scan(
		&i.ID,
		&i.TeamID,
		&i.UserID,
		&i.Role,
		&i.Status,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const listTeamMemberships = `-- name: ListTeamMemberships :many
SELECT id, team_id, user_id, role, status, created_at, updated_at FROM team_memberships ORDER BY id LIMIT $1 OFFSET $2
`

type ListTeamMembershipsParams struct {
	Limit  int32 `json:"limit"`
	Offset int32 `json:"offset"`
}

func (q *Queries) ListTeamMemberships(ctx context.Context, arg ListTeamMembershipsParams) ([]TeamMembership, error) {
	rows, err := q.db.Query(ctx, listTeamMemberships, arg.Limit, arg.Offset)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []TeamMembership
	for rows.Next() {
		var i TeamMembership
		if err := rows.Scan(
			&i.ID,
			&i.TeamID,
			&i.UserID,
			&i.Role,
			&i.Status,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listTeamMembershipsByTeam = `-- name: ListTeamMembershipsByTeam :many
SELECT id, team_id, user_id, role, status, created_at, updated_at FROM team_memberships WHERE team_id = $1 ORDER BY id
`

func (q *Queries) ListTeamMembershipsByTeam(ctx context.Context, teamID int64) ([]TeamMembership, error) {
	rows, err := q.db.Query(ctx, listTeamMembershipsByTeam, teamID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []TeamMembership
	for rows.Next() {
		var i TeamMembership
		if err := rows.Scan(
			&i.ID,
			&i.TeamID,
			&i.UserID,
			&i.Role,
			&i.Status,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listTeamMembershipsByUser = `-- name: ListTeamMembershipsByUser :many
SELECT id, team_id, user_id, role, status, created_at, updated_at FROM team_memberships WHERE user_id = $1 ORDER BY id
`

func (q *Queries) ListTeamMembershipsByUser(ctx context.Context, userID int64) ([]TeamMembership, error) {
	rows, err := q.db.Query(ctx, listTeamMembershipsByUser, userID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []TeamMembership
	for rows.Next() {
		var i TeamMembership
		if err := rows.Scan(
			&i.ID,
			&i.TeamID,
			&i.UserID,
			&i.Role,
			&i.Status,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateMembershipRole = `-- name: UpdateMembershipRole :one
UPDATE team_memberships SET role = $2, updated_at = now()
WHERE id = $1 RETURNING id, team_id, user_id, role, status, created_at, updated_at
`

type UpdateMembershipRoleParams struct {
	ID   int64   `json:"id"`
	Role *string `json:"role"`
}

func (q *Queries) UpdateMembershipRole(ctx context.Context, arg UpdateMembershipRoleParams) (TeamMembership, error) {
	row := q.db.QueryRow(ctx, updateMembershipRole, arg.ID, arg.Role)
	var i TeamMembership
	err := row.Scan(
		&i.ID,
		&i.TeamID,
		&i.UserID,
		&i.Role,
		&i.Status,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const updateMembershipStatus = `-- name: UpdateMembershipStatus :one
UPDATE team_memberships SET status = $2, updated_at = now()
WHERE id = $1 RETURNING id, team_id, user_id, role, status, created_at, updated_at
`

type UpdateMembershipStatusParams struct {
	ID     int64   `json:"id"`
	Status *string `json:"status"`
}

func (q *Queries) UpdateMembershipStatus(ctx context.Context, arg UpdateMembershipStatusParams) (TeamMembership, error) {
	row := q.db.QueryRow(ctx, updateMembershipStatus, arg.ID, arg.Status)
	var i TeamMembership
	err := row.Scan(
		&i.ID,
		&i.TeamID,
		&i.UserID,
		&i.Role,
		&i.Status,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const updateTeamMembership = `-- name: UpdateTeamMembership :one
UPDATE team_memberships SET role = COALESCE($2, role),
    status = COALESCE($3, status),
    updated_at = now()
WHERE id = $1 RETURNING id, team_id, user_id, role, status, created_at, updated_at
`

type UpdateTeamMembershipParams struct {
	ID     int64   `json:"id"`
	Role   *string `json:"role"`
	Status *string `json:"status"`
}

func (q *Queries) UpdateTeamMembership(ctx context.Context, arg UpdateTeamMembershipParams) (TeamMembership, error) {
	row := q.db.QueryRow(ctx, updateTeamMembership, arg.ID, arg.Role, arg.Status)
	var i TeamMembership
	err := row.Scan(
		&i.ID,
		&i.TeamID,
		&i.UserID,
		&i.Role,
		&i.Status,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}
