// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: team_membership_events.sql

package db

import (
	"context"
)

const countEventsByTeam = `-- name: CountEventsByTeam :one
SELECT count(*) FROM team_membership_events WHERE team_id = $1
`

func (q *Queries) CountEventsByTeam(ctx context.Context, teamID int64) (int64, error) {
	row := q.db.QueryRow(ctx, countEventsByTeam, teamID)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const createEvent = `-- name: CreateEvent :one
INSERT INTO team_membership_events (team_id, user_id, actor_id, action, from_role, to_role, from_status, to_status)
VALUES ($1, $2, $3, $4, $5, $6, $7, $8)
RETURNING id, team_id, user_id, actor_id, action, from_role, to_role, from_status, to_status, created_at, updated_at
`

type CreateEventParams struct {
	TeamID     int64   `json:"team_id"`
	UserID     int64   `json:"user_id"`
	ActorID    *int32  `json:"actor_id"`
	Action     string  `json:"action"`
	FromRole   *string `json:"from_role"`
	ToRole     *string `json:"to_role"`
	FromStatus *string `json:"from_status"`
	ToStatus   *string `json:"to_status"`
}

func (q *Queries) CreateEvent(ctx context.Context, arg CreateEventParams) (TeamMembershipEvent, error) {
	row := q.db.QueryRow(ctx, createEvent,
		arg.TeamID,
		arg.UserID,
		arg.ActorID,
		arg.Action,
		arg.FromRole,
		arg.ToRole,
		arg.FromStatus,
		arg.ToStatus,
	)
	var i TeamMembershipEvent
	err := row.Scan(
		&i.ID,
		&i.TeamID,
		&i.UserID,
		&i.ActorID,
		&i.Action,
		&i.FromRole,
		&i.ToRole,
		&i.FromStatus,
		&i.ToStatus,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const listEventsByTeam = `-- name: ListEventsByTeam :many
SELECT id, team_id, user_id, actor_id, action, from_role, to_role, from_status, to_status, created_at, updated_at FROM team_membership_events WHERE team_id = $1 ORDER BY created_at DESC LIMIT $2 OFFSET $3
`

type ListEventsByTeamParams struct {
	TeamID int64 `json:"team_id"`
	Limit  int32 `json:"limit"`
	Offset int32 `json:"offset"`
}

func (q *Queries) ListEventsByTeam(ctx context.Context, arg ListEventsByTeamParams) ([]TeamMembershipEvent, error) {
	rows, err := q.db.Query(ctx, listEventsByTeam, arg.TeamID, arg.Limit, arg.Offset)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []TeamMembershipEvent
	for rows.Next() {
		var i TeamMembershipEvent
		if err := rows.Scan(
			&i.ID,
			&i.TeamID,
			&i.UserID,
			&i.ActorID,
			&i.Action,
			&i.FromRole,
			&i.ToRole,
			&i.FromStatus,
			&i.ToStatus,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
