// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: universities.sql

package db

import (
	"context"
)

const countUniversities = `-- name: CountUniversities :one
SELECT count(*) FROM universities
WHERE (name ILIKE '%' || $1 || '%' OR $1 IS NULL)
`

func (q *Queries) CountUniversities(ctx context.Context, searchQuery *string) (int64, error) {
	row := q.db.QueryRow(ctx, countUniversities, searchQuery)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const createUniversity = `-- name: CreateUniversity :one
INSERT INTO universities (name, site_url, avatar_url)
VALUES ($1, $2, $3)
RETURNING id, name, site_url, avatar_url, created_at, updated_at
`

type CreateUniversityParams struct {
	Name      *string `json:"name"`
	SiteUrl   *string `json:"site_url"`
	AvatarUrl *string `json:"avatar_url"`
}

func (q *Queries) CreateUniversity(ctx context.Context, arg CreateUniversityParams) (University, error) {
	row := q.db.QueryRow(ctx, createUniversity, arg.Name, arg.SiteUrl, arg.AvatarUrl)
	var i University
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.SiteUrl,
		&i.AvatarUrl,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const deleteUniversity = `-- name: DeleteUniversity :exec
DELETE FROM universities WHERE id = $1
`

func (q *Queries) DeleteUniversity(ctx context.Context, id int64) error {
	_, err := q.db.Exec(ctx, deleteUniversity, id)
	return err
}

const getUniversityByID = `-- name: GetUniversityByID :one
SELECT id, name, site_url, avatar_url, created_at, updated_at FROM universities WHERE id = $1
`

func (q *Queries) GetUniversityByID(ctx context.Context, id int64) (University, error) {
	row := q.db.QueryRow(ctx, getUniversityByID, id)
	var i University
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.SiteUrl,
		&i.AvatarUrl,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const listUniversities = `-- name: ListUniversities :many
SELECT id, name, site_url, avatar_url, created_at, updated_at FROM universities
WHERE (name ILIKE '%' || $3 || '%' OR $3 IS NULL)
ORDER BY id LIMIT $1 OFFSET $2
`

type ListUniversitiesParams struct {
	Limit       int32   `json:"limit"`
	Offset      int32   `json:"offset"`
	SearchQuery *string `json:"search_query"`
}

func (q *Queries) ListUniversities(ctx context.Context, arg ListUniversitiesParams) ([]University, error) {
	rows, err := q.db.Query(ctx, listUniversities, arg.Limit, arg.Offset, arg.SearchQuery)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []University
	for rows.Next() {
		var i University
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.SiteUrl,
			&i.AvatarUrl,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateUniversity = `-- name: UpdateUniversity :one
UPDATE universities SET name = COALESCE($2, name),
    site_url = COALESCE($3, site_url),
    avatar_url = COALESCE($4, avatar_url),
    updated_at = now()
WHERE id = $1 RETURNING id, name, site_url, avatar_url, created_at, updated_at
`

type UpdateUniversityParams struct {
	ID        int64   `json:"id"`
	Name      *string `json:"name"`
	SiteUrl   *string `json:"site_url"`
	AvatarUrl *string `json:"avatar_url"`
}

func (q *Queries) UpdateUniversity(ctx context.Context, arg UpdateUniversityParams) (University, error) {
	row := q.db.QueryRow(ctx, updateUniversity,
		arg.ID,
		arg.Name,
		arg.SiteUrl,
		arg.AvatarUrl,
	)
	var i University
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.SiteUrl,
		&i.AvatarUrl,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}
