// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: users.sql

package db

import (
	"context"
)

const countUsers = `-- name: CountUsers :one
SELECT count(*) FROM users
WHERE (
  user_name ILIKE '%' || $1 || '%'
  OR display_name ILIKE '%' || $1 || '%'
  OR $1 IS NULL
)
`

func (q *Queries) CountUsers(ctx context.Context, searchQuery *string) (int64, error) {
	row := q.db.QueryRow(ctx, countUsers, searchQuery)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const createUser = `-- name: CreateUser :one
INSERT INTO users (user_name, display_name, role, rating, avatar_url, password_digest)
VALUES ($1, $2, $3, $4, $5, $6)
RETURNING id, user_name, display_name, role, rating, avatar_url, password_digest, created_at, updated_at
`

type CreateUserParams struct {
	UserName       string  `json:"user_name"`
	DisplayName    string  `json:"display_name"`
	Role           string  `json:"role"`
	Rating         int32   `json:"rating"`
	AvatarUrl      *string `json:"avatar_url"`
	PasswordDigest *string `json:"password_digest"`
}

func (q *Queries) CreateUser(ctx context.Context, arg CreateUserParams) (User, error) {
	row := q.db.QueryRow(ctx, createUser,
		arg.UserName,
		arg.DisplayName,
		arg.Role,
		arg.Rating,
		arg.AvatarUrl,
		arg.PasswordDigest,
	)
	var i User
	err := row.Scan(
		&i.ID,
		&i.UserName,
		&i.DisplayName,
		&i.Role,
		&i.Rating,
		&i.AvatarUrl,
		&i.PasswordDigest,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const deleteUser = `-- name: DeleteUser :exec
DELETE FROM users
WHERE id = $1
`

func (q *Queries) DeleteUser(ctx context.Context, id int64) error {
	_, err := q.db.Exec(ctx, deleteUser, id)
	return err
}

const getUserByID = `-- name: GetUserByID :one
SELECT id, user_name, display_name, role, rating, avatar_url, password_digest, created_at, updated_at FROM users
WHERE id = $1
`

func (q *Queries) GetUserByID(ctx context.Context, id int64) (User, error) {
	row := q.db.QueryRow(ctx, getUserByID, id)
	var i User
	err := row.Scan(
		&i.ID,
		&i.UserName,
		&i.DisplayName,
		&i.Role,
		&i.Rating,
		&i.AvatarUrl,
		&i.PasswordDigest,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getUserByUserName = `-- name: GetUserByUserName :one
SELECT id, user_name, display_name, role, rating, avatar_url, password_digest, created_at, updated_at FROM users
WHERE user_name = $1
`

func (q *Queries) GetUserByUserName(ctx context.Context, userName string) (User, error) {
	row := q.db.QueryRow(ctx, getUserByUserName, userName)
	var i User
	err := row.Scan(
		&i.ID,
		&i.UserName,
		&i.DisplayName,
		&i.Role,
		&i.Rating,
		&i.AvatarUrl,
		&i.PasswordDigest,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const listUsers = `-- name: ListUsers :many
SELECT id, user_name, display_name, role, rating, avatar_url, password_digest, created_at, updated_at FROM users
WHERE (
  user_name ILIKE '%' || $3 || '%'
  OR display_name ILIKE '%' || $3 || '%'
  OR $3 IS NULL
)
ORDER BY id
LIMIT $1 OFFSET $2
`

type ListUsersParams struct {
	Limit       int32   `json:"limit"`
	Offset      int32   `json:"offset"`
	SearchQuery *string `json:"search_query"`
}

func (q *Queries) ListUsers(ctx context.Context, arg ListUsersParams) ([]User, error) {
	rows, err := q.db.Query(ctx, listUsers, arg.Limit, arg.Offset, arg.SearchQuery)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []User
	for rows.Next() {
		var i User
		if err := rows.Scan(
			&i.ID,
			&i.UserName,
			&i.DisplayName,
			&i.Role,
			&i.Rating,
			&i.AvatarUrl,
			&i.PasswordDigest,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateUserProfile = `-- name: UpdateUserProfile :one
UPDATE users
SET display_name = $2,
    avatar_url = COALESCE($3, avatar_url),
    password_digest = COALESCE($4, password_digest),
    updated_at = now()
WHERE id = $1
RETURNING id, user_name, display_name, role, rating, avatar_url, password_digest, created_at, updated_at
`

type UpdateUserProfileParams struct {
	ID             int64   `json:"id"`
	DisplayName    string  `json:"display_name"`
	AvatarUrl      *string `json:"avatar_url"`
	PasswordDigest *string `json:"password_digest"`
}

func (q *Queries) UpdateUserProfile(ctx context.Context, arg UpdateUserProfileParams) (User, error) {
	row := q.db.QueryRow(ctx, updateUserProfile,
		arg.ID,
		arg.DisplayName,
		arg.AvatarUrl,
		arg.PasswordDigest,
	)
	var i User
	err := row.Scan(
		&i.ID,
		&i.UserName,
		&i.DisplayName,
		&i.Role,
		&i.Rating,
		&i.AvatarUrl,
		&i.PasswordDigest,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const updateUserRating = `-- name: UpdateUserRating :one
UPDATE users
SET rating = $2,
    updated_at = now()
WHERE id = $1
RETURNING id, user_name, display_name, role, rating, avatar_url, password_digest, created_at, updated_at
`

type UpdateUserRatingParams struct {
	ID     int64 `json:"id"`
	Rating int32 `json:"rating"`
}

func (q *Queries) UpdateUserRating(ctx context.Context, arg UpdateUserRatingParams) (User, error) {
	row := q.db.QueryRow(ctx, updateUserRating, arg.ID, arg.Rating)
	var i User
	err := row.Scan(
		&i.ID,
		&i.UserName,
		&i.DisplayName,
		&i.Role,
		&i.Rating,
		&i.AvatarUrl,
		&i.PasswordDigest,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const updateUserRole = `-- name: UpdateUserRole :one
UPDATE users
SET role = $2,
    updated_at = now()
WHERE id = $1
RETURNING id, user_name, display_name, role, rating, avatar_url, password_digest, created_at, updated_at
`

type UpdateUserRoleParams struct {
	ID   int64  `json:"id"`
	Role string `json:"role"`
}

func (q *Queries) UpdateUserRole(ctx context.Context, arg UpdateUserRoleParams) (User, error) {
	row := q.db.QueryRow(ctx, updateUserRole, arg.ID, arg.Role)
	var i User
	err := row.Scan(
		&i.ID,
		&i.UserName,
		&i.DisplayName,
		&i.Role,
		&i.Rating,
		&i.AvatarUrl,
		&i.PasswordDigest,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}
