// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: users.sql

package db

import (
	"context"
)

const clearUserTeamCaptaincy = `-- name: ClearUserTeamCaptaincy :exec
UPDATE teams
SET captain_id = NULL
WHERE captain_id = $1
`

func (q *Queries) ClearUserTeamCaptaincy(ctx context.Context, captainID *int32) error {
	_, err := q.db.Exec(ctx, clearUserTeamCaptaincy, captainID)
	return err
}

const countUsers = `-- name: CountUsers :one
SELECT count(*) FROM users
WHERE (
  user_name ILIKE '%' || $1 || '%'
  OR display_name ILIKE '%' || $1 || '%'
  OR $1 IS NULL
)
`

func (q *Queries) CountUsers(ctx context.Context, searchQuery *string) (int64, error) {
	row := q.db.QueryRow(ctx, countUsers, searchQuery)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const createUser = `-- name: CreateUser :one
INSERT INTO users (user_name, display_name, role, rating, avatar_url, password_digest)
VALUES ($1, $2, $3, $4, $5, $6)
RETURNING id, user_name, display_name, role, rating, avatar_url, password_digest, created_at, updated_at, bio, telegram, github, email, is_blocked, blocked_at, last_login_ip, last_login_at, language, theme
`

type CreateUserParams struct {
	UserName       string  `json:"user_name"`
	DisplayName    string  `json:"display_name"`
	Role           string  `json:"role"`
	Rating         int32   `json:"rating"`
	AvatarUrl      *string `json:"avatar_url"`
	PasswordDigest *string `json:"password_digest"`
}

func (q *Queries) CreateUser(ctx context.Context, arg CreateUserParams) (User, error) {
	row := q.db.QueryRow(ctx, createUser,
		arg.UserName,
		arg.DisplayName,
		arg.Role,
		arg.Rating,
		arg.AvatarUrl,
		arg.PasswordDigest,
	)
	var i User
	err := row.Scan(
		&i.ID,
		&i.UserName,
		&i.DisplayName,
		&i.Role,
		&i.Rating,
		&i.AvatarUrl,
		&i.PasswordDigest,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.Bio,
		&i.Telegram,
		&i.Github,
		&i.Email,
		&i.IsBlocked,
		&i.BlockedAt,
		&i.LastLoginIp,
		&i.LastLoginAt,
		&i.Language,
		&i.Theme,
	)
	return i, err
}

const deleteUser = `-- name: DeleteUser :exec
DELETE FROM users
WHERE id = $1
`

func (q *Queries) DeleteUser(ctx context.Context, id int64) error {
	_, err := q.db.Exec(ctx, deleteUser, id)
	return err
}

const getUserByID = `-- name: GetUserByID :one
SELECT id, user_name, display_name, role, rating, avatar_url, password_digest, created_at, updated_at, bio, telegram, github, email, is_blocked, blocked_at, last_login_ip, last_login_at, language, theme FROM users
WHERE id = $1
`

func (q *Queries) GetUserByID(ctx context.Context, id int64) (User, error) {
	row := q.db.QueryRow(ctx, getUserByID, id)
	var i User
	err := row.Scan(
		&i.ID,
		&i.UserName,
		&i.DisplayName,
		&i.Role,
		&i.Rating,
		&i.AvatarUrl,
		&i.PasswordDigest,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.Bio,
		&i.Telegram,
		&i.Github,
		&i.Email,
		&i.IsBlocked,
		&i.BlockedAt,
		&i.LastLoginIp,
		&i.LastLoginAt,
		&i.Language,
		&i.Theme,
	)
	return i, err
}

const getUserByUserName = `-- name: GetUserByUserName :one
SELECT id, user_name, display_name, role, rating, avatar_url, password_digest, created_at, updated_at, bio, telegram, github, email, is_blocked, blocked_at, last_login_ip, last_login_at, language, theme FROM users
WHERE user_name = $1
`

func (q *Queries) GetUserByUserName(ctx context.Context, userName string) (User, error) {
	row := q.db.QueryRow(ctx, getUserByUserName, userName)
	var i User
	err := row.Scan(
		&i.ID,
		&i.UserName,
		&i.DisplayName,
		&i.Role,
		&i.Rating,
		&i.AvatarUrl,
		&i.PasswordDigest,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.Bio,
		&i.Telegram,
		&i.Github,
		&i.Email,
		&i.IsBlocked,
		&i.BlockedAt,
		&i.LastLoginIp,
		&i.LastLoginAt,
		&i.Language,
		&i.Theme,
	)
	return i, err
}

const listUsers = `-- name: ListUsers :many
SELECT id, user_name, display_name, role, rating, avatar_url, password_digest, created_at, updated_at, bio, telegram, github, email, is_blocked, blocked_at, last_login_ip, last_login_at, language, theme FROM users
WHERE (
  user_name ILIKE '%' || $3 || '%'
  OR display_name ILIKE '%' || $3 || '%'
  OR $3 IS NULL
)
ORDER BY id
LIMIT $1 OFFSET $2
`

type ListUsersParams struct {
	Limit       int32   `json:"limit"`
	Offset      int32   `json:"offset"`
	SearchQuery *string `json:"search_query"`
}

func (q *Queries) ListUsers(ctx context.Context, arg ListUsersParams) ([]User, error) {
	rows, err := q.db.Query(ctx, listUsers, arg.Limit, arg.Offset, arg.SearchQuery)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []User
	for rows.Next() {
		var i User
		if err := rows.Scan(
			&i.ID,
			&i.UserName,
			&i.DisplayName,
			&i.Role,
			&i.Rating,
			&i.AvatarUrl,
			&i.PasswordDigest,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.Bio,
			&i.Telegram,
			&i.Github,
			&i.Email,
			&i.IsBlocked,
			&i.BlockedAt,
			&i.LastLoginIp,
			&i.LastLoginAt,
			&i.Language,
			&i.Theme,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const setUserAvatar = `-- name: SetUserAvatar :one
UPDATE users
SET avatar_url = $2,
    updated_at = now()
WHERE id = $1
RETURNING id, user_name, display_name, role, rating, avatar_url, password_digest, created_at, updated_at, bio, telegram, github, email, is_blocked, blocked_at, last_login_ip, last_login_at, language, theme
`

type SetUserAvatarParams struct {
	ID        int64   `json:"id"`
	AvatarUrl *string `json:"avatar_url"`
}

func (q *Queries) SetUserAvatar(ctx context.Context, arg SetUserAvatarParams) (User, error) {
	row := q.db.QueryRow(ctx, setUserAvatar, arg.ID, arg.AvatarUrl)
	var i User
	err := row.Scan(
		&i.ID,
		&i.UserName,
		&i.DisplayName,
		&i.Role,
		&i.Rating,
		&i.AvatarUrl,
		&i.PasswordDigest,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.Bio,
		&i.Telegram,
		&i.Github,
		&i.Email,
		&i.IsBlocked,
		&i.BlockedAt,
		&i.LastLoginIp,
		&i.LastLoginAt,
		&i.Language,
		&i.Theme,
	)
	return i, err
}

const setUserBlocked = `-- name: SetUserBlocked :one
UPDATE users
SET is_blocked = $2,
    blocked_at = CASE WHEN $2 THEN now() ELSE NULL END,
    updated_at = now()
WHERE id = $1
RETURNING id, user_name, display_name, role, rating, avatar_url, password_digest, created_at, updated_at, bio, telegram, github, email, is_blocked, blocked_at, last_login_ip, last_login_at, language, theme
`

type SetUserBlockedParams struct {
	ID        int64 `json:"id"`
	IsBlocked bool  `json:"is_blocked"`
}

func (q *Queries) SetUserBlocked(ctx context.Context, arg SetUserBlockedParams) (User, error) {
	row := q.db.QueryRow(ctx, setUserBlocked, arg.ID, arg.IsBlocked)
	var i User
	err := row.Scan(
		&i.ID,
		&i.UserName,
		&i.DisplayName,
		&i.Role,
		&i.Rating,
		&i.AvatarUrl,
		&i.PasswordDigest,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.Bio,
		&i.Telegram,
		&i.Github,
		&i.Email,
		&i.IsBlocked,
		&i.BlockedAt,
		&i.LastLoginIp,
		&i.LastLoginAt,
		&i.Language,
		&i.Theme,
	)
	return i, err
}

const setUserLastLogin = `-- name: SetUserLastLogin :one
UPDATE users
SET last_login_ip = $2,
    last_login_at = now()
WHERE id = $1
RETURNING id, user_name, display_name, role, rating, avatar_url, password_digest, created_at, updated_at, bio, telegram, github, email, is_blocked, blocked_at, last_login_ip, last_login_at, language, theme
`

type SetUserLastLoginParams struct {
	ID          int64   `json:"id"`
	LastLoginIp *string `json:"last_login_ip"`
}

func (q *Queries) SetUserLastLogin(ctx context.Context, arg SetUserLastLoginParams) (User, error) {
	row := q.db.QueryRow(ctx, setUserLastLogin, arg.ID, arg.LastLoginIp)
	var i User
	err := row.Scan(
		&i.ID,
		&i.UserName,
		&i.DisplayName,
		&i.Role,
		&i.Rating,
		&i.AvatarUrl,
		&i.PasswordDigest,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.Bio,
		&i.Telegram,
		&i.Github,
		&i.Email,
		&i.IsBlocked,
		&i.BlockedAt,
		&i.LastLoginIp,
		&i.LastLoginAt,
		&i.Language,
		&i.Theme,
	)
	return i, err
}

const updateUserPassword = `-- name: UpdateUserPassword :one
UPDATE users
SET password_digest = $2,
    updated_at = now()
WHERE id = $1
RETURNING id, user_name, display_name, role, rating, avatar_url, password_digest, created_at, updated_at, bio, telegram, github, email, is_blocked, blocked_at, last_login_ip, last_login_at, language, theme
`

type UpdateUserPasswordParams struct {
	ID             int64   `json:"id"`
	PasswordDigest *string `json:"password_digest"`
}

func (q *Queries) UpdateUserPassword(ctx context.Context, arg UpdateUserPasswordParams) (User, error) {
	row := q.db.QueryRow(ctx, updateUserPassword, arg.ID, arg.PasswordDigest)
	var i User
	err := row.Scan(
		&i.ID,
		&i.UserName,
		&i.DisplayName,
		&i.Role,
		&i.Rating,
		&i.AvatarUrl,
		&i.PasswordDigest,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.Bio,
		&i.Telegram,
		&i.Github,
		&i.Email,
		&i.IsBlocked,
		&i.BlockedAt,
		&i.LastLoginIp,
		&i.LastLoginAt,
		&i.Language,
		&i.Theme,
	)
	return i, err
}

const updateUserProfile = `-- name: UpdateUserProfile :one
UPDATE users
SET display_name = $2,
    avatar_url = COALESCE($3, avatar_url),
    password_digest = COALESCE($4, password_digest),
    updated_at = now()
WHERE id = $1
RETURNING id, user_name, display_name, role, rating, avatar_url, password_digest, created_at, updated_at, bio, telegram, github, email, is_blocked, blocked_at, last_login_ip, last_login_at, language, theme
`

type UpdateUserProfileParams struct {
	ID             int64   `json:"id"`
	DisplayName    string  `json:"display_name"`
	AvatarUrl      *string `json:"avatar_url"`
	PasswordDigest *string `json:"password_digest"`
}

func (q *Queries) UpdateUserProfile(ctx context.Context, arg UpdateUserProfileParams) (User, error) {
	row := q.db.QueryRow(ctx, updateUserProfile,
		arg.ID,
		arg.DisplayName,
		arg.AvatarUrl,
		arg.PasswordDigest,
	)
	var i User
	err := row.Scan(
		&i.ID,
		&i.UserName,
		&i.DisplayName,
		&i.Role,
		&i.Rating,
		&i.AvatarUrl,
		&i.PasswordDigest,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.Bio,
		&i.Telegram,
		&i.Github,
		&i.Email,
		&i.IsBlocked,
		&i.BlockedAt,
		&i.LastLoginIp,
		&i.LastLoginAt,
		&i.Language,
		&i.Theme,
	)
	return i, err
}

const updateUserProfileAdmin = `-- name: UpdateUserProfileAdmin :one
UPDATE users
SET display_name = $2,
    avatar_url = COALESCE($3, avatar_url),
    password_digest = COALESCE($4, password_digest),
    bio = $5,
    telegram = $6,
    github = $7,
    email = $8,
    language = $9,
    theme = $10,
    updated_at = now()
WHERE id = $1
RETURNING id, user_name, display_name, role, rating, avatar_url, password_digest, created_at, updated_at, bio, telegram, github, email, is_blocked, blocked_at, last_login_ip, last_login_at, language, theme
`

type UpdateUserProfileAdminParams struct {
	ID             int64   `json:"id"`
	DisplayName    string  `json:"display_name"`
	AvatarUrl      *string `json:"avatar_url"`
	PasswordDigest *string `json:"password_digest"`
	Bio            *string `json:"bio"`
	Telegram       *string `json:"telegram"`
	Github         *string `json:"github"`
	Email          *string `json:"email"`
	Language       string  `json:"language"`
	Theme          string  `json:"theme"`
}

func (q *Queries) UpdateUserProfileAdmin(ctx context.Context, arg UpdateUserProfileAdminParams) (User, error) {
	row := q.db.QueryRow(ctx, updateUserProfileAdmin,
		arg.ID,
		arg.DisplayName,
		arg.AvatarUrl,
		arg.PasswordDigest,
		arg.Bio,
		arg.Telegram,
		arg.Github,
		arg.Email,
		arg.Language,
		arg.Theme,
	)
	var i User
	err := row.Scan(
		&i.ID,
		&i.UserName,
		&i.DisplayName,
		&i.Role,
		&i.Rating,
		&i.AvatarUrl,
		&i.PasswordDigest,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.Bio,
		&i.Telegram,
		&i.Github,
		&i.Email,
		&i.IsBlocked,
		&i.BlockedAt,
		&i.LastLoginIp,
		&i.LastLoginAt,
		&i.Language,
		&i.Theme,
	)
	return i, err
}

const updateUserRating = `-- name: UpdateUserRating :one
UPDATE users
SET rating = $2,
    updated_at = now()
WHERE id = $1
RETURNING id, user_name, display_name, role, rating, avatar_url, password_digest, created_at, updated_at, bio, telegram, github, email, is_blocked, blocked_at, last_login_ip, last_login_at, language, theme
`

type UpdateUserRatingParams struct {
	ID     int64 `json:"id"`
	Rating int32 `json:"rating"`
}

func (q *Queries) UpdateUserRating(ctx context.Context, arg UpdateUserRatingParams) (User, error) {
	row := q.db.QueryRow(ctx, updateUserRating, arg.ID, arg.Rating)
	var i User
	err := row.Scan(
		&i.ID,
		&i.UserName,
		&i.DisplayName,
		&i.Role,
		&i.Rating,
		&i.AvatarUrl,
		&i.PasswordDigest,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.Bio,
		&i.Telegram,
		&i.Github,
		&i.Email,
		&i.IsBlocked,
		&i.BlockedAt,
		&i.LastLoginIp,
		&i.LastLoginAt,
		&i.Language,
		&i.Theme,
	)
	return i, err
}

const updateUserRole = `-- name: UpdateUserRole :one
UPDATE users
SET role = $2,
    updated_at = now()
WHERE id = $1
RETURNING id, user_name, display_name, role, rating, avatar_url, password_digest, created_at, updated_at, bio, telegram, github, email, is_blocked, blocked_at, last_login_ip, last_login_at, language, theme
`

type UpdateUserRoleParams struct {
	ID   int64  `json:"id"`
	Role string `json:"role"`
}

func (q *Queries) UpdateUserRole(ctx context.Context, arg UpdateUserRoleParams) (User, error) {
	row := q.db.QueryRow(ctx, updateUserRole, arg.ID, arg.Role)
	var i User
	err := row.Scan(
		&i.ID,
		&i.UserName,
		&i.DisplayName,
		&i.Role,
		&i.Rating,
		&i.AvatarUrl,
		&i.PasswordDigest,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.Bio,
		&i.Telegram,
		&i.Github,
		&i.Email,
		&i.IsBlocked,
		&i.BlockedAt,
		&i.LastLoginIp,
		&i.LastLoginAt,
		&i.Language,
		&i.Theme,
	)
	return i, err
}
