// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: writeups.sql

package db

import (
	"context"
)

const createWriteup = `-- name: CreateWriteup :one
INSERT INTO writeups (game_id, team_id, title, url)
VALUES ($1, $2, $3, $4)
RETURNING id, game_id, team_id, title, url, created_at, updated_at
`

type CreateWriteupParams struct {
	GameID int64  `json:"game_id"`
	TeamID int64  `json:"team_id"`
	Title  string `json:"title"`
	Url    string `json:"url"`
}

func (q *Queries) CreateWriteup(ctx context.Context, arg CreateWriteupParams) (Writeup, error) {
	row := q.db.QueryRow(ctx, createWriteup,
		arg.GameID,
		arg.TeamID,
		arg.Title,
		arg.Url,
	)
	var i Writeup
	err := row.Scan(
		&i.ID,
		&i.GameID,
		&i.TeamID,
		&i.Title,
		&i.Url,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const deleteWriteup = `-- name: DeleteWriteup :exec
DELETE FROM writeups WHERE id = $1
`

func (q *Queries) DeleteWriteup(ctx context.Context, id int64) error {
	_, err := q.db.Exec(ctx, deleteWriteup, id)
	return err
}

const getWriteupByID = `-- name: GetWriteupByID :one
SELECT id, game_id, team_id, title, url, created_at, updated_at FROM writeups WHERE id = $1
`

func (q *Queries) GetWriteupByID(ctx context.Context, id int64) (Writeup, error) {
	row := q.db.QueryRow(ctx, getWriteupByID, id)
	var i Writeup
	err := row.Scan(
		&i.ID,
		&i.GameID,
		&i.TeamID,
		&i.Title,
		&i.Url,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const listAllWriteups = `-- name: ListAllWriteups :many
SELECT id, game_id, team_id, title, url, created_at, updated_at FROM writeups ORDER BY created_at DESC, id DESC
`

func (q *Queries) ListAllWriteups(ctx context.Context) ([]Writeup, error) {
	rows, err := q.db.Query(ctx, listAllWriteups)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Writeup
	for rows.Next() {
		var i Writeup
		if err := rows.Scan(
			&i.ID,
			&i.GameID,
			&i.TeamID,
			&i.Title,
			&i.Url,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listWriteupsByGame = `-- name: ListWriteupsByGame :many
SELECT id, game_id, team_id, title, url, created_at, updated_at FROM writeups WHERE game_id = $1 ORDER BY created_at DESC, id DESC
`

func (q *Queries) ListWriteupsByGame(ctx context.Context, gameID int64) ([]Writeup, error) {
	rows, err := q.db.Query(ctx, listWriteupsByGame, gameID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Writeup
	for rows.Next() {
		var i Writeup
		if err := rows.Scan(
			&i.ID,
			&i.GameID,
			&i.TeamID,
			&i.Title,
			&i.Url,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listWriteupsByGameAndTeam = `-- name: ListWriteupsByGameAndTeam :many
SELECT id, game_id, team_id, title, url, created_at, updated_at FROM writeups WHERE game_id = $1 AND team_id = $2 ORDER BY created_at DESC, id DESC
`

type ListWriteupsByGameAndTeamParams struct {
	GameID int64 `json:"game_id"`
	TeamID int64 `json:"team_id"`
}

func (q *Queries) ListWriteupsByGameAndTeam(ctx context.Context, arg ListWriteupsByGameAndTeamParams) ([]Writeup, error) {
	rows, err := q.db.Query(ctx, listWriteupsByGameAndTeam, arg.GameID, arg.TeamID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Writeup
	for rows.Next() {
		var i Writeup
		if err := rows.Scan(
			&i.ID,
			&i.GameID,
			&i.TeamID,
			&i.Title,
			&i.Url,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listWriteupsByTeam = `-- name: ListWriteupsByTeam :many
SELECT id, game_id, team_id, title, url, created_at, updated_at FROM writeups WHERE team_id = $1 ORDER BY created_at DESC, id DESC
`

func (q *Queries) ListWriteupsByTeam(ctx context.Context, teamID int64) ([]Writeup, error) {
	rows, err := q.db.Query(ctx, listWriteupsByTeam, teamID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Writeup
	for rows.Next() {
		var i Writeup
		if err := rows.Scan(
			&i.ID,
			&i.GameID,
			&i.TeamID,
			&i.Title,
			&i.Url,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
