version: 2

formatters:
  enable:
    - gofumpt
    - gci

run:
  timeout: 5m

linters:
  enable:
    - govet
    - staticcheck
    - errcheck
    - revive

linters-settings:
  revive:
    rules:
      - name: exported
        disabled: true

issues:
  exclude-dirs:
    - gen/
    - internal/repository/db/
