version: "2"
run:
  go: "1.26"
linters:
  enable:
    - bodyclose
    - canonicalheader
    - copyloopvar
    - dogsled
    # - dupl
    - dupword
    - errcheck
    - errname
    # - errorlint
    - exhaustive
    - fatcontext
    # - funlen
    # - gochecknoglobals
    - gochecknoinits
    - goconst
    - gocritic
    - gocyclo
    - goprintffuncname
    - gosec
    - govet
    - inamedparam
    - ineffassign
    # - lll
    - loggercheck
    - mirror
    - misspell
    - mnd
    - nakedret
    - noctx
    - nolintlint
    - perfsprint
    - revive
    - rowserrcheck
    - staticcheck
    - testifylint
    - thelper
    - unconvert
    - unparam
    - unused
    - usestdlibvars
    - whitespace
  settings:
    misspell:
      locale: US
    revive:
      rules:
        - name: blank-imports
        - name: context-as-argument
          arguments:
            - allowTypesBefore: '*testing.T'
        - name: dot-imports
        - name: empty-block
        - name: error-naming
        - name: error-return
        - name: error-strings
        - name: errorf
        - name: increment-decrement
        - name: indent-error-flow
        - name: range
        - name: receiver-naming
        - name: redefines-builtin-id
        - name: superfluous-else
        - name: time-naming
        - name: unexported-return
        - name: unreachable-code
        - name: var-declaration
        - name: var-naming
        - name: unused-parameter
        - name: import-shadowing
        - name: exported
  exclusions:
    generated: lax
    presets:
      - comments
      - common-false-positives
      - legacy
      - std-error-handling
    rules:
      - linters:
          - revive
        path: (.+)_test.go
        text: ^(dot-imports|add-constant)
      - linters:
          - goconst
          - gocyclo
          - gosec
          - mnd
        path: (.+)_test.go
      - linters:
          - gocyclo
          - mnd
        path: cmd/seed/main.go
      - linters:
          - revive
        text: ^(var-naming|exported)
    paths:
      - third_party$
      - builtin$
      - examples$
      - web/node_modules
formatters:
  enable:
    - gci
  settings:
    gci:
      sections:
        - standard
        - default
        - localmodule
  exclusions:
    generated: lax
    paths:
      - third_party$
      - builtin$
      - examples$
      - web/node_modules
