//go:build ignore
// +build ignore

package main

import (
	"bytes"
	"flag"
	"fmt"
	"go/format"
	"log"
	"os"
	"sort"
	"strings"

	"github.com/getkin/kin-openapi/openapi3"
)

const requiredRoleExtension = "x-required-role"

func main() {
	input := flag.String("input", "api/openapi.yaml", "OpenAPI spec file")
	output := flag.String("output", "gen/httpserver/roles.gen.go", "generated Go output file")
	pkg := flag.String("package", "httpserver", "generated Go package")
	flag.Parse()

	spec, err := openapi3.NewLoader().LoadFromFile(*input)
	if err != nil {
		log.Fatalf("load OpenAPI spec: %v", err)
	}

	roles, err := collectRoles(spec)
	if err != nil {
		log.Fatal(err)
	}

	source, err := render(*pkg, roles)
	if err != nil {
		log.Fatal(err)
	}

	if err := os.WriteFile(*output, source, 0o644); err != nil {
		log.Fatalf("write %s: %v", *output, err)
	}
}

func collectRoles(spec *openapi3.T) (map[string]string, error) {
	roles := make(map[string]string)
	for _, path := range spec.Paths.Keys() {
		pathItem := spec.Paths.Value(path)
		if pathItem == nil {
			continue
		}

		operations := pathItem.Operations()
		methods := make([]string, 0, len(operations))
		for method := range operations {
			methods = append(methods, method)
		}
		sort.Strings(methods)

		for _, method := range methods {
			operation := operations[method]
			if operation == nil {
				continue
			}

			role, ok, err := requiredRole(operation)
			if err != nil {
				return nil, fmt.Errorf("%s %s: %w", method, path, err)
			}
			if !ok {
				continue
			}

			roles[method+" "+path] = role
		}
	}

	return roles, nil
}

func requiredRole(operation *openapi3.Operation) (string, bool, error) {
	value, ok := operation.Extensions[requiredRoleExtension]
	if !ok {
		return "", false, nil
	}

	role, ok := value.(string)
	if !ok {
		return "", false, fmt.Errorf("%s must be a string", requiredRoleExtension)
	}
	role = strings.TrimSpace(role)
	if role == "" {
		return "", false, fmt.Errorf("%s must not be empty", requiredRoleExtension)
	}
	if !validRole(role) {
		return "", false, fmt.Errorf("unknown required role %q", role)
	}

	return role, true, nil
}

func validRole(role string) bool {
	switch role {
	case "guest", "player", "admin":
		return true
	default:
		return false
	}
}

func render(pkg string, roles map[string]string) ([]byte, error) {
	var buf bytes.Buffer
	fmt.Fprintf(&buf, "// Code generated by scripts/openapi-required-roles.go; DO NOT EDIT.\n\n")
	fmt.Fprintf(&buf, "package %s\n\n", pkg)
	fmt.Fprintln(&buf, "// OperationRequiredRoles maps OpenAPI operation keys to the minimum role declared via x-required-role.")
	fmt.Fprintln(&buf, "var OperationRequiredRoles = map[string]string{")

	keys := make([]string, 0, len(roles))
	for key := range roles {
		keys = append(keys, key)
	}
	sort.Strings(keys)

	for _, key := range keys {
		fmt.Fprintf(&buf, "\t%q: %q,\n", key, roles[key])
	}
	fmt.Fprintln(&buf, "}")

	source, err := format.Source(buf.Bytes())
	if err != nil {
		return nil, fmt.Errorf("format generated source: %w", err)
	}

	return source, nil
}
